name: Cron Test

# Add this block right here
permissions:
  contents: read

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "cron working"
      
